### ISSUE TITLE
Implement deployment for taggloo.im using GitHub Actions

### ISSUE THREAD

**Issue by ProgramX-NPledger** [ProgramX-NPledger/Taggloo4#243]
## Consider:

* Limiting deployments to 1 (Concurrency)
* Permissions (only permit certain deployers)
* Quality Gates (code must pass quality before being deployed)
* Deploy to Environment `taggloo_im`, which appears on home page

## Resources

* https://docs.github.com/en/actions/use-cases-and-examples/deploying/deploying-with-github-actions
*

**Comment by ProgramX-NPledger** [comment]
```
name: taggloo_im

concurrency:
  group: taggloo_im
  cancel-in-progress: true

```
